/* SPDX-License-Identifier: GPL-3.0-or-later */
#include "interop_buffer_probe.hpp"
#include "lsfg-vk-common/helpers/owned_fd.hpp"
#include "lsfg-vk-common/vulkan/physical_device.hpp"
#include "lsfg-vk-common/vulkan/vulkan.hpp"
#include <algorithm>
#include <cerrno>
#include <cstring>
#include <fcntl.h>
#include <gbm.h>
#include <iostream>
#include <stdexcept>
#include <sys/stat.h>
#include <unistd.h>
#include <utility>
#include <vulkan/vulkan_core.h>

namespace probe = lsfgvk::cli::interop_buffer_probe;
namespace {
constexpr VkDeviceSize SIZE = 64 * 1024;
constexpr uint32_t PATTERN_A = 0xA5A5A5A5;
constexpr uint32_t PATTERN_B = 0x5A5A5A5A;
struct Failure : std::runtime_error { using std::runtime_error::runtime_error; };
template<class T> T load(PFN_vkGetDeviceProcAddr g, VkDevice d, const char* n) {
    auto p = reinterpret_cast<T>(g(d, n)); if (!p) throw Failure(std::string("DEVICE_FUNCTION_MISSING: ") + n); return p;
}
struct Device {
    VkPhysicalDevice physical{}; VkDevice device{}; VkQueue queue{}; uint32_t family{};
    VkPhysicalDeviceMemoryProperties memoryProperties{};
    PFN_vkDestroyDevice destroy{}; PFN_vkCreateBuffer createBuffer{}; PFN_vkDestroyBuffer destroyBuffer{};
    PFN_vkGetBufferMemoryRequirements requirements{}; PFN_vkAllocateMemory allocate{}; PFN_vkFreeMemory freeMemory{};
    PFN_vkBindBufferMemory bind{}; PFN_vkGetMemoryFdPropertiesKHR fdProperties{};
    PFN_vkCreateCommandPool createPool{}; PFN_vkDestroyCommandPool destroyPool{};
    PFN_vkAllocateCommandBuffers allocCmd{}; PFN_vkBeginCommandBuffer begin{}; PFN_vkEndCommandBuffer end{};
    PFN_vkCmdPipelineBarrier barrier{}; PFN_vkCmdFillBuffer fill{}; PFN_vkCmdCopyBuffer copy{};
    PFN_vkCreateFence createFence{}; PFN_vkDestroyFence destroyFence{}; PFN_vkWaitForFences waitFence{};
    PFN_vkQueueSubmit submit{}; PFN_vkMapMemory map{}; PFN_vkUnmapMemory unmap{};
    PFN_vkInvalidateMappedMemoryRanges invalidate{};
    Device()=default; Device(const Device&)=delete; Device& operator=(const Device&)=delete;
    ~Device(){ if(device && destroy) destroy(device,nullptr); }
};
struct Buffer { Device* d{}; VkBuffer buffer{}; VkDeviceMemory memory{}; VkMemoryPropertyFlags flags{};
    Buffer()=default; explicit Buffer(Device* device):d(device){} Buffer(const Buffer&)=delete; Buffer& operator=(const Buffer&)=delete;
    Buffer(Buffer&& o) noexcept:d(std::exchange(o.d,nullptr)),buffer(std::exchange(o.buffer,VK_NULL_HANDLE)),memory(std::exchange(o.memory,VK_NULL_HANDLE)),flags(o.flags){}
    ~Buffer(){ if(d&&buffer)d->destroyBuffer(d->device,buffer,nullptr); if(d&&memory)d->freeMemory(d->device,memory,nullptr); }
};
struct GbmPayload { ls::OwnedFd node; gbm_device* dev{}; gbm_bo* bo{}; ls::OwnedFd fd; VkDeviceSize size{};
    ~GbmPayload(){ fd.reset(); if(bo)gbm_bo_destroy(bo); if(dev)gbm_device_destroy(dev); }
};
std::vector<std::string> extensions(const vk::VulkanInstanceInventoryFuncs& f,VkPhysicalDevice p){return vk::enumerateDeviceExtensionNames(f,p);}
bool has(const std::vector<std::string>& e,const char* n){return std::ranges::binary_search(e,std::string(n));}
std::unique_ptr<Device> makeDevice(const vk::VulkanInstanceInventoryFuncs& f,VkPhysicalDevice p,const char* label){
    auto ex=extensions(f,p); if(!has(ex,VK_KHR_EXTERNAL_MEMORY_FD_EXTENSION_NAME)||!has(ex,VK_EXT_EXTERNAL_MEMORY_DMA_BUF_EXTENSION_NAME)||!has(ex,VK_EXT_QUEUE_FAMILY_FOREIGN_EXTENSION_NAME)) throw Failure(std::string(label)+"_REQUIRED_EXTENSION_MISSING");
    uint32_t count{}; f.GetPhysicalDeviceQueueFamilyProperties(p,&count,nullptr); std::vector<VkQueueFamilyProperties> q(count); f.GetPhysicalDeviceQueueFamilyProperties(p,&count,q.data());
    auto it=std::ranges::find_if(q,[](const auto& x){return (x.queueFlags&VK_QUEUE_TRANSFER_BIT)!=0;}); if(it==q.end())throw Failure(std::string(label)+"_NO_TRANSFER_QUEUE"); uint32_t family=static_cast<uint32_t>(it-q.begin()); float priority=1;
    VkDeviceQueueCreateInfo qi{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,nullptr,0,family,1,&priority}; const char* names[]={VK_KHR_EXTERNAL_MEMORY_FD_EXTENSION_NAME,VK_EXT_EXTERNAL_MEMORY_DMA_BUF_EXTENSION_NAME,VK_EXT_QUEUE_FAMILY_FOREIGN_EXTENSION_NAME};
    VkDeviceCreateInfo ci{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,nullptr,0,1,&qi,0,nullptr,3,names,nullptr}; auto owner=std::make_unique<Device>(); Device& d=*owner; d.physical=p; d.family=family; auto r=f.CreateDevice(p,&ci,nullptr,&d.device); if(r!=VK_SUCCESS)throw Failure(std::string(label)+"_CREATE_FAILED VkResult="+std::to_string(r));
    auto g=f.GetDeviceProcAddr; d.destroy=load<PFN_vkDestroyDevice>(g,d.device,"vkDestroyDevice"); d.createBuffer=load<PFN_vkCreateBuffer>(g,d.device,"vkCreateBuffer"); d.destroyBuffer=load<PFN_vkDestroyBuffer>(g,d.device,"vkDestroyBuffer"); d.requirements=load<PFN_vkGetBufferMemoryRequirements>(g,d.device,"vkGetBufferMemoryRequirements"); d.allocate=load<PFN_vkAllocateMemory>(g,d.device,"vkAllocateMemory"); d.freeMemory=load<PFN_vkFreeMemory>(g,d.device,"vkFreeMemory"); d.bind=load<PFN_vkBindBufferMemory>(g,d.device,"vkBindBufferMemory"); d.fdProperties=load<PFN_vkGetMemoryFdPropertiesKHR>(g,d.device,"vkGetMemoryFdPropertiesKHR"); d.createPool=load<PFN_vkCreateCommandPool>(g,d.device,"vkCreateCommandPool"); d.destroyPool=load<PFN_vkDestroyCommandPool>(g,d.device,"vkDestroyCommandPool"); d.allocCmd=load<PFN_vkAllocateCommandBuffers>(g,d.device,"vkAllocateCommandBuffers"); d.begin=load<PFN_vkBeginCommandBuffer>(g,d.device,"vkBeginCommandBuffer"); d.end=load<PFN_vkEndCommandBuffer>(g,d.device,"vkEndCommandBuffer"); d.barrier=load<PFN_vkCmdPipelineBarrier>(g,d.device,"vkCmdPipelineBarrier"); d.fill=load<PFN_vkCmdFillBuffer>(g,d.device,"vkCmdFillBuffer"); d.copy=load<PFN_vkCmdCopyBuffer>(g,d.device,"vkCmdCopyBuffer"); d.createFence=load<PFN_vkCreateFence>(g,d.device,"vkCreateFence"); d.destroyFence=load<PFN_vkDestroyFence>(g,d.device,"vkDestroyFence"); d.waitFence=load<PFN_vkWaitForFences>(g,d.device,"vkWaitForFences"); d.submit=load<PFN_vkQueueSubmit>(g,d.device,"vkQueueSubmit"); d.map=load<PFN_vkMapMemory>(g,d.device,"vkMapMemory"); d.unmap=load<PFN_vkUnmapMemory>(g,d.device,"vkUnmapMemory"); d.invalidate=load<PFN_vkInvalidateMappedMemoryRanges>(g,d.device,"vkInvalidateMappedMemoryRanges"); auto getQueue=load<PFN_vkGetDeviceQueue>(g,d.device,"vkGetDeviceQueue"); getQueue(d.device,family,0,&d.queue); f.GetPhysicalDeviceMemoryProperties(p,&d.memoryProperties); return owner;
}
VkBuffer createRaw(Device& d,bool external,VkDeviceSize size){VkExternalMemoryBufferCreateInfo ei{VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO,nullptr,VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT};VkBufferCreateInfo ci{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,external?&ei:nullptr,0,size,VK_BUFFER_USAGE_TRANSFER_SRC_BIT|VK_BUFFER_USAGE_TRANSFER_DST_BIT,VK_SHARING_MODE_EXCLUSIVE,0,nullptr};VkBuffer b{};auto r=d.createBuffer(d.device,&ci,nullptr,&b);if(r!=VK_SUCCESS)throw Failure("BUFFER_CREATE_FAILED VkResult="+std::to_string(r));return b;}
uint32_t choose(Device& d,uint32_t bits,VkMemoryPropertyFlags required,VkMemoryPropertyFlags preferred=0){std::vector<uint32_t> fs(d.memoryProperties.memoryTypeCount);for(uint32_t i=0;i<fs.size();++i)fs[i]=d.memoryProperties.memoryTypes[i].propertyFlags;auto v=probe::selectMemoryType(bits,fs,required,preferred);if(!v)throw Failure("NO_MEMORY_TYPE_INTERSECTION");return *v;}
Buffer importShared(Device& d,ls::OwnedFd& fd,VkDeviceSize backing,const char* label){Buffer out{&d};out.buffer=createRaw(d,true,SIZE);VkMemoryRequirements req{};d.requirements(d.device,out.buffer,&req);VkMemoryFdPropertiesKHR fp{VK_STRUCTURE_TYPE_MEMORY_FD_PROPERTIES_KHR};auto r=d.fdProperties(d.device,VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT,fd.get(),&fp);std::cout<<label<<" requirements size="<<req.size<<" alignment="<<req.alignment<<" typeBits=0x"<<std::hex<<req.memoryTypeBits<<" fdBits=0x"<<fp.memoryTypeBits<<std::dec<<"\n";if(r!=VK_SUCCESS)throw Failure(std::string(label)+"_FD_PROPERTIES_FAILED VkResult="+std::to_string(r));if(backing<req.size)throw Failure("DMA_BUF_SIZE_INVALID");uint32_t bits=probe::usableMemoryTypes(fp.memoryTypeBits,req.memoryTypeBits);if(!bits)throw Failure(std::string(label)+"_NO_MEMORY_TYPE_INTERSECTION");uint32_t index=choose(d,bits,0);out.flags=d.memoryProperties.memoryTypes[index].propertyFlags;VkImportMemoryFdInfoKHR ii{VK_STRUCTURE_TYPE_IMPORT_MEMORY_FD_INFO_KHR,nullptr,VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT,fd.get()};VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,&ii,backing,index};r=d.allocate(d.device,&ai,nullptr,&out.memory);if(r!=VK_SUCCESS)throw Failure(std::string(label)+"_IMPORT_FAILED VkResult="+std::to_string(r));static_cast<void>(fd.release());r=d.bind(d.device,out.buffer,out.memory,0);if(r!=VK_SUCCESS)throw Failure(std::string(label)+"_BIND_FAILED VkResult="+std::to_string(r));std::cout<<label<<" intersection=0x"<<std::hex<<bits<<std::dec<<" memoryType="<<index<<" flags=0x"<<std::hex<<out.flags<<std::dec<<"\n";return out;}
Buffer staging(Device& d){Buffer b{&d};b.buffer=createRaw(d,false,SIZE);VkMemoryRequirements r{};d.requirements(d.device,b.buffer,&r);uint32_t i=choose(d,r.memoryTypeBits,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT,VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);b.flags=d.memoryProperties.memoryTypes[i].propertyFlags;VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,nullptr,r.size,i};if(d.allocate(d.device,&ai,nullptr,&b.memory)!=VK_SUCCESS)throw Failure("STAGING_ALLOC_FAILED");if(d.bind(d.device,b.buffer,b.memory,0)!=VK_SUCCESS)throw Failure("STAGING_BIND_FAILED");return b;}
void phase(Device& d,VkBuffer shared,VkBuffer readback,uint32_t acquireAccess,uint32_t fillValue,bool doCopy,bool finalRelease,const char* label){VkCommandPool pool{};VkCommandPoolCreateInfo pi{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,nullptr,VK_COMMAND_POOL_CREATE_TRANSIENT_BIT,d.family};if(d.createPool(d.device,&pi,nullptr,&pool)!=VK_SUCCESS)throw Failure(std::string(label)+"_COMMAND_POOL_FAILED");VkCommandBuffer cmd{};VkCommandBufferAllocateInfo ai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,nullptr,pool,VK_COMMAND_BUFFER_LEVEL_PRIMARY,1};d.allocCmd(d.device,&ai,&cmd);VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};d.begin(cmd,&bi);VkBufferMemoryBarrier ac{VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,nullptr,0,acquireAccess,VK_QUEUE_FAMILY_FOREIGN_EXT,d.family,shared,0,SIZE};d.barrier(cmd,VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,1,&ac,0,nullptr);if(doCopy){VkBufferCopy c{0,0,SIZE};d.copy(cmd,shared,readback,1,&c);VkMemoryBarrier m{VK_STRUCTURE_TYPE_MEMORY_BARRIER,nullptr,VK_ACCESS_TRANSFER_READ_BIT,VK_ACCESS_TRANSFER_WRITE_BIT};d.barrier(cmd,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,1,&m,0,nullptr,0,nullptr);}if(fillValue)d.fill(cmd,shared,0,SIZE,fillValue);if(finalRelease){VkBufferMemoryBarrier rel{VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,nullptr,fillValue?VK_ACCESS_TRANSFER_WRITE_BIT:VK_ACCESS_TRANSFER_READ_BIT,0,d.family,VK_QUEUE_FAMILY_FOREIGN_EXT,shared,0,SIZE};d.barrier(cmd,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,0,0,nullptr,1,&rel,0,nullptr);}d.end(cmd);VkFence fence{};VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};d.createFence(d.device,&fi,nullptr,&fence);VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO,nullptr,0,nullptr,nullptr,1,&cmd,0,nullptr};auto r=d.submit(d.queue,1,&si,fence);if(r!=VK_SUCCESS)throw Failure(std::string(label)+"_SUBMIT_FAILED VkResult="+std::to_string(r));r=d.waitFence(d.device,1,&fence,VK_TRUE,UINT64_MAX);d.destroyFence(d.device,fence,nullptr);d.destroyPool(d.device,pool,nullptr);if(r!=VK_SUCCESS)throw Failure(std::string(label)+"_FENCE_FAILED VkResult="+std::to_string(r));}
probe::PatternResult read(Device& d,Buffer& b,uint32_t expected){void* p{};if(d.map(d.device,b.memory,0,SIZE,0,&p)!=VK_SUCCESS)throw Failure("STAGING_MAP_FAILED");if(!(b.flags&VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)){VkMappedMemoryRange range{VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE,nullptr,b.memory,0,VK_WHOLE_SIZE};d.invalidate(d.device,1,&range);}auto result=probe::verifyPattern(static_cast<uint32_t*>(p),SIZE/4,expected);d.unmap(d.device,b.memory);return result;}
}

uint32_t probe::usableMemoryTypes(uint32_t a,uint32_t b){return a&b;}
std::optional<uint32_t> probe::selectMemoryType(uint32_t bits,const std::vector<uint32_t>& flags,uint32_t required,uint32_t preferred){for(uint32_t pass=0;pass<2;++pass)for(uint32_t i=0;i<flags.size();++i)if((bits&(1u<<i))&&(flags[i]&required)==required&&(pass||((flags[i]&preferred)==preferred)))return i;return std::nullopt;}
probe::PatternResult probe::verifyPattern(const uint32_t* p,size_t n,uint32_t e){for(size_t i=0;i<n;++i)if(p[i]!=e)return{false,i};return{true,n};}
std::optional<probe::Options> probe::parse(const std::vector<std::string>& a,std::string& error){Options o;bool aa=false,da=false,db=false;for(size_t i=0;i<a.size();++i){if(i+1>=a.size()){error="missing option value";return{};}try{if(a[i]=="--allocator"){o.allocator=a[++i];aa=true;}else if(a[i]=="--device-a"){o.deviceA=std::stoul(a[++i]);da=true;}else if(a[i]=="--device-b"){o.deviceB=std::stoul(a[++i]);db=true;}else{error="unknown option: "+a[i];return{};}}catch(...){error="invalid option value";return{};}}if(!aa||!da||!db){error="--allocator, --device-a and --device-b are required";return{};}if(o.deviceA==o.deviceB){error="device A and B must differ";return{};}return o;}
int probe::run(const Options& o){try{GbmPayload gbm;gbm.node.reset(::open(o.allocator.c_str(),O_RDWR|O_CLOEXEC));if(!gbm.node)throw Failure("ALLOCATOR_OPEN_FAILED errno="+std::to_string(errno));gbm.dev=gbm_create_device(gbm.node.get());if(!gbm.dev)throw Failure("GBM_DEVICE_CREATE_FAILED errno="+std::to_string(errno));gbm.bo=gbm_bo_create(gbm.dev,256,256,GBM_FORMAT_R8,GBM_BO_USE_LINEAR|GBM_BO_USE_RENDERING);if(!gbm.bo)throw Failure("GBM_ALLOC_FAILED errno="+std::to_string(errno));gbm.fd.reset(gbm_bo_get_fd(gbm.bo));if(!gbm.fd)throw Failure("DMA_BUF_FD_FAILED errno="+std::to_string(errno));off_t end=lseek(gbm.fd.get(),0,SEEK_END);if(end<0)throw Failure("DMA_BUF_SIZE_INVALID errno="+std::to_string(errno));gbm.size=static_cast<VkDeviceSize>(end);lseek(gbm.fd.get(),0,SEEK_SET);ls::OwnedFd fdA(fcntl(gbm.fd.get(),F_DUPFD_CLOEXEC,0)),fdB(fcntl(gbm.fd.get(),F_DUPFD_CLOEXEC,0));if(!fdA||!fdB)throw Failure("DMA_BUF_FD_FAILED errno="+std::to_string(errno));vk::VulkanInventoryInstance instance{"lsfg-vk-cli",{2,0,0},"lsfg-vk-cli",{2,0,0}};auto physical=vk::enumeratePhysicalDevices(instance.fi(),instance.inst());if(o.deviceA>=physical.size()||o.deviceB>=physical.size())throw Failure("DEVICE_INDEX_OUT_OF_RANGE");auto idA=vk::getPhysicalDeviceIdentity(instance.fi(),physical[o.deviceA]);auto idB=vk::getPhysicalDeviceIdentity(instance.fi(),physical[o.deviceB]);std::cout<<"Allocator: GBM\nAllocator node: "<<o.allocator<<"\nLogical size: "<<SIZE<<"\nDMA_BUF size: "<<gbm.size<<"\nDevice A: "<<idA.name<<"\nDevice B: "<<idB.name<<"\n";auto ownerA=makeDevice(instance.fi(),physical[o.deviceA],"A"),ownerB=makeDevice(instance.fi(),physical[o.deviceB],"B");Device& a=*ownerA;Device& b=*ownerB;Buffer sharedA=importShared(a,fdA,gbm.size,"A"),sharedB=importShared(b,fdB,gbm.size,"B"),stageA=staging(a),stageB=staging(b);phase(a,sharedA.buffer,VK_NULL_HANDLE,VK_ACCESS_TRANSFER_WRITE_BIT,PATTERN_A,false,true,"A");phase(b,sharedB.buffer,stageB.buffer,VK_ACCESS_TRANSFER_READ_BIT,PATTERN_B,true,true,"B");auto ab=read(b,stageB,PATTERN_A);if(!ab.matches)throw Failure("A_TO_B_DATA_MISMATCH index="+std::to_string(ab.mismatchIndex));phase(a,sharedA.buffer,stageA.buffer,VK_ACCESS_TRANSFER_READ_BIT,0,true,true,"A");auto ba=read(a,stageA,PATTERN_B);if(!ba.matches)throw Failure("B_TO_A_DATA_MISMATCH index="+std::to_string(ba.mismatchIndex));std::cout<<"A_TO_B_DATA_CHECK PASS\nB_TO_A_DATA_CHECK PASS\nFINAL: CROSS_DEVICE_DMA_BUF_BUFFER_PASS\n";return EXIT_SUCCESS;}catch(const std::exception& e){std::cerr<<"FINAL: "<<e.what()<<"\n";return EXIT_FAILURE;}}
